spring:
  application:
    name: mes-collection
management:
  security:
    enabled: false
springdoc:
  api-docs:
    enabled: true
  packages-to-scan: fr.pe.incub.mescomics
  swagger-ui:
    path: /swagger.html


